package keymap

import (
	"bufio"
	"os"
	"path/filepath"
	"strings"
)

// Config 对应 bindings.ini 的完整内容。
type Config struct {
	GameProcess  string            // [General] 游戏进程名
	OnlyInGame   bool              // 仅在游戏前台时生效
	StartEnabled bool              // 保存后是否自动启动映射
	Bindings     map[string]string // 操作ID -> 键名
}

// DefaultConfig 返回带默认键位的配置。
func DefaultConfig() *Config {
	cfg := &Config{
		GameProcess:  "NBA2K27.exe",
		OnlyInGame:   true,
		StartEnabled: true,
		Bindings:     map[string]string{},
	}
	for _, b := range Bindings {
		cfg.Bindings[b.ID] = b.Default
	}
	return cfg
}

// ConfigPath 返回配置文件路径：默认与可执行文件同目录。
func ConfigPath(exePath string) string {
	if exePath == "" {
		exePath = "."
	}
	return filepath.Join(filepath.Dir(exePath), "bindings.ini")
}

// LoadConfig 读取 bindings.ini；文件不存在时返回默认配置。
// 未知键值会被忽略，保证旧版本配置仍可读取。
func LoadConfig(path string) (*Config, error) {
	cfg := DefaultConfig()
	f, err := os.Open(path)
	if err != nil {
		if os.IsNotExist(err) {
			return cfg, nil
		}
		return nil, err
	}
	defer f.Close()

	section := ""
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, ";") || strings.HasPrefix(line, "#") {
			continue
		}
		if strings.HasPrefix(line, "[") && strings.HasSuffix(line, "]") {
			section = strings.ToLower(line[1 : len(line)-1])
			continue
		}
		eq := strings.IndexByte(line, '=')
		if eq < 0 {
			continue
		}
		k := strings.TrimSpace(line[:eq])
		v := strings.TrimSpace(line[eq+1:])
		switch section {
		case "general":
			switch strings.ToLower(k) {
			case "gameprocess":
				cfg.GameProcess = v
			case "onlyingame":
				cfg.OnlyInGame = parseBool(v, cfg.OnlyInGame)
			case "startenabled":
				cfg.StartEnabled = parseBool(v, cfg.StartEnabled)
			}
		case "bindings":
			// 仅接受已知操作；值必须可解析为有效键名。
			if _, known := BindingIndex[k]; known {
				if _, err := Parse(v); err == nil {
					cfg.Bindings[k] = strings.ToUpper(v)
				}
			}
		}
	}
	if err := sc.Err(); err != nil {
		return nil, err
	}
	return cfg, nil
}

// SaveConfig 将配置写回 bindings.ini（保持原文件注释结构）。
func SaveConfig(path string, cfg *Config) error {
	var sb strings.Builder
	sb.WriteString("; NBA 2K27 Keyboard Remap - generated by GUI\n")
	sb.WriteString("; 本文件由图形界面自动生成，请勿手动编辑\n\n")
	sb.WriteString("[General]\n")
	sb.WriteString("GameProcess=" + cfg.GameProcess + "\n")
	sb.WriteString("OnlyInGame=" + boolInt(cfg.OnlyInGame) + "\n")
	sb.WriteString("StartEnabled=" + boolInt(cfg.StartEnabled) + "\n\n")
	sb.WriteString("[Bindings]\n")
	for _, b := range Bindings {
		name, ok := cfg.Bindings[b.ID]
		if !ok || name == "" {
			name = b.Default
		}
		sb.WriteString(b.ID + "=" + name + "\n")
	}
	return os.WriteFile(path, []byte(sb.String()), 0o644)
}

func parseBool(s string, def bool) bool {
	switch strings.ToLower(strings.TrimSpace(s)) {
	case "1", "true", "yes", "on":
		return true
	case "0", "false", "no", "off":
		return false
	}
	return def
}

func boolInt(b bool) string {
	if b {
		return "1"
	}
	return "0"
}
